# Define the deployment for Eureka Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server    # Name of the deployment
  labels:
    app: eureka-server   # Label to identify the deployment
spec:
  replicas: 1            # Number of replicas to run
  selector:
    matchLabels:
      app: eureka-server # Label selector for pods
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: familyhub/eurekaserver:0.0.1-SNAPSHOT  # Your Eureka Server image
        ports:
        - containerPort: 8761    # Default Eureka port
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
---
# Define the service for Eureka Server
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server   # Select pods with this label
  ports:
    - port: 8761         # Port exposed by the service
      targetPort: 8761   # Port on the container
  type: ClusterIP        # Internal cluster IP 