apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Define the deployment for Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana            # Name of the deployment
  labels:
    app: grafana          # Label to identify the deployment
spec:
  replicas: 1             # Number of replicas to run
  selector:
    matchLabels:
      app: grafana        # Label selector for pods
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest  # Official Grafana image
        ports:
        - containerPort: 3000    # Default Grafana port
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"         # Default admin password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
---
# Define the service for Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana          # Select pods with this label
  ports:
    - port: 3000          # Port exposed by the service
      targetPort: 3000    # Port on the container
  type: LoadBalancer      # External access type 