# Define the deployment for User Expense Tracker service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-expense-tracker    # Name of the deployment
  labels:
    app: user-expense-tracker   # Label to identify the deployment
spec:
  replicas: 1                   # Number of replicas to run
  selector:
    matchLabels:
      app: user-expense-tracker # Label selector for pods
  template:
    metadata:
      labels:
        app: user-expense-tracker
    spec:
      containers:
      - name: user-expense-tracker
        image: familyhub/user-expense-tracker:0.0.1-SNAPSHOT  # Your service image
        ports:
        - containerPort: 8083    # Service port
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"  # Eureka server URL
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/familyhub"  # MongoDB connection URL
---
# Define the service for User Expense Tracker
apiVersion: v1
kind: Service
metadata:
  name: user-expense-tracker
spec:
  selector:
    app: user-expense-tracker   # Select pods with this label
  ports:
    - port: 8083               # Port exposed by the service
      targetPort: 8083         # Port on the container
  type: ClusterIP              # Internal cluster IP 